name: large_batch

defaults:
  - data: ImageNetAnimals
  - impl: default
  - server: honest-but-curious
  - user: local_gradient
  - _self_
model: ResNet152

# Server and user:
num_queries: 1

# User data:
user:
  num_data_points: 128
