type: default

attack_type: optimization   # analytic, equation solver
label_strategy: wainakh-simple  # Only in effect if the user does not provide labels
# Label strategy options are 'iDLG', 'analytic', 'yin', 'wainakh-simple', 'wainakh-whitebox', 'random', 'exhaustive'

objective:
  type: euclidean
  scale: 1.0
  task_regularization: 0.0

restarts:
  num_trials: 1
  scoring: euclidean

init: randn
normalize_gradients: False

optim:
  optimizer: Adam
  signed: False
  step_size: 1.0
  boxed: False
  max_iterations: 400
  step_size_decay:
  langevin_noise: 0.0
  warmup: 0

  callback: 100  # Print objective value every callback many iterations

regularization:

impl:
  dtype: float
  mixed_precision: False
  JIT: # bembel with care
